name: 'check-cve'
description: 'Send GitHub vulnerability alerts to multiple platforms'
author: '@kunalnagar'
inputs:
  token:
    description: 'GitHub Personal Access Token'
  slack_webhook:
    description: 'Slack Webhook URL'
  pager_duty_integration_key:
    description: 'Pager Duty Integration Key. More instructions: https://support.pagerduty.com/docs/services-and-integrations'
  count:
    description: 'Number of vulnerability alerts to send'
    default: 20
branding:
  icon: 'alert-octagon'
  color: 'red'
runs:
  using: 'node12'
  main: 'dist/index.js'
