name: 'check-cve'
description: 'Send GitHub vulnerability alerts to multiple platforms like Slack, PagerDuty.'
author: '@kunalnagar'
inputs:
  token:
    description: 'GitHub Personal Access Token'
  microsoft_teams_webhook:
    description: 'Microsoft Teams Channel Webhook URL. More info: https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook'
  slack_webhook:
    description: 'Slack Webhook URL. More info: https://api.slack.com/messaging/webhooks'
  pager_duty_integration_key:
    description: 'Pager Duty Integration Key. More info: https://support.pagerduty.com/docs/services-and-integrations'
  zenduty_api_key:
    description: 'Create a Zenduty API Key by visiting Account Settings > API Keys'
  zenduty_service_id:
    description: 'Zenduty Service ID: https://docs.zenduty.com/docs/services'
  zenduty_escalation_policy_id:
    description: 'Zenduty Escalation Policy ID: https://docs.zenduty.com/docs/escalationpolicies'
  count:
    description: 'Number of vulnerability alerts to send'
    default: 20
branding:
  icon: 'alert-octagon'
  color: 'red'
runs:
  using: 'node12'
  main: 'dist/index.js'
